
module.exports={
    SECRET_KEY:"ashdoashdoihsaoidhjsaoihdoiahsfiusduhcvbsdjghcvuhdsagfuisgdfiuysgdf",
    EMAIL_EXIST:"Email Already Exits",
    INVALID_LOGIN_MESSAGE:"Email or password is invalid",
    SUCCESS_MESSAGE:"Success",
    ACTIVE:"ACTIVE",
    INACTIVE:"INACTIVE",
    AUTHENTICATION_FAILED:"Authentication failed",
    INVALID_EMAIL:"Invalid email ID",
    PASSWORD_RESET:"Password reset success",
    EMAIL_OTP:"OTP sent to your email",
    GROUP_CREATED:"Group successfully  created",
    ALLOWED:"ALLOWED",
    DENIED:"DENIED",
    POST:"POST",
    GET:"GET",
    UPDATE:"UPDATE",
    DELETE:"DELETE",
    UN_AUTH:"You don't have access to this API",
    GROUP_EXISTS:"Group Exists",
    INVALID_ID:"Invalid ID ",
    UPDATED_SUCCESS:"Updated Successfully",
    FAILED_UPDATE:"Failed to update",
    INVALID_STATUS:"Invalid status",
    PROVIDE_FIELD:"Provide necessary field",
    DELETE_SUCCESS:"Successfully Deleted",
    DELETE_FAILED:"Failed to delete",
    SUCCESS_ADD:"Successfully added",
    USER_PRESENT:"User already present",
    USER_NOT_EXIST:"User doesn't exist",
    STARTED:"STARTED",
    FAILED:"FAILED",
    TEST_ALREADY_STARTED:"Test Already Started",
    COMPLETED:"COMPLETED"
}